### ISSUE TITLE
sbit WDT_IO=P0^3;  converted (wrongly) into  `__sbit __at () WDT_IO=P0^3`

### ISSUE THREAD

**Issue by allan-simon** [ywaby/keil2sdcc#1]
also would you consider a pull request to put the `f""` syntax into a `"".format()` syntax , so that your program is compatible with python3.5 ? (which most of us are stuck with on our distro :) )

thanks again for your repository

**Comment by ywaby** [comment]
@allan-simon what is your distro?

**Comment by allan-simon** [comment]
I'm on ubuntu 16.04

**Comment by ywaby** [comment]
I have make a python 3.5 branch, and fix bug recent. 
Need you to test it , as there not python 3.5 in my distro 
1. 
```
python3.5 test.py
```
2. upload ./test/test.sdcc.c
